---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace:  media
  labels:
    app: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app: jellyfin
    spec:
      restartPolicy: Always
      # initContainers:
      # # remove the default config, so i can attach the desired one later
      # - name: init-qbittorrent-qbt-config
      #   image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
      #   command: ["sh", "-c", "rm /config/database.xml"]
      #   volumeMounts:
      #   - name: jf-config
      #     mountPath:  /config
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:12.1ubu2604-ls50
          # get the filename from Mobius Backup dataset:/mnt/mobius/Backup/jellyfin/jellyfin-backup-*.zip
          # args: ["--restore-archive", "/config/data/data/backups/jellyfin-backup-20260919084708.zip"]
          resources:
            limits:
              cpu: 12
              memory: 6Gi
            requests:
              cpu: 1
              memory: 512Mi
          ports:
            - containerPort: 8096
          volumeMounts:
          - name: jf-movies
            mountPath:  /Movies
          - name: jf-shows
            mountPath:  /TV
          - name: jf-config
            mountPath:  /config
          - name: jf-backup
            mountPath:  /config/data/data/backups
          # - name: jellyfin-db-config
          #   mountPath: /config/database.xml            
          #   subPath: database-optimistic.xml
          env:
          - name: PUID
            valueFrom:
              configMapKeyRef:
                name: jf-env
                key:  PUID
          - name: PGID
            valueFrom:
              configMapKeyRef:
                name: jf-env
                key:  PGID
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: jf-env
                key:  TZ
      volumes:
      - name: jf-movies
        hostPath:
          path: /mnt/mobius/Video/Movies
      - name: jf-shows
        hostPath:
          path: /mnt/mobius/Video/TV-shows
      - name: jf-config
        persistentVolumeClaim:
          claimName:  jf-config-data
      # - name: jellyfin-db-config
      #   configMap:
      #     name: jellyfin-db-configmap
      - name: jf-backup
        persistentVolumeClaim:
          claimName:  jellyfin-nfs-bkup-pvc
          