---
resources:
  - deployment.yml
  - service.yml
  - env-configmap.yml
  - pvc.yml
  - pv.yml

configMapGenerator:
- name: jellyfin-db-configmap
  files:
  - config/database-optimistic.xml
#   - config/database-nolock.xml
#   - config/database-pessimistic.xml