---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nfs-bkup-pv
  namespace:  media
spec:
  capacity:
    storage: 20Gi
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/storage_node/Backup/jellyfin
    server: 192.168.11.2
  persistentVolumeReclaimPolicy: Retain