---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-config-data
  namespace:  media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-nfs-bkup-pvc
  namespace:  media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 20Gi
  volumeName: jellyfin-nfs-bkup-pv