---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-config-data
  namespace:  media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
