---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  labels:
    app: homer
spec:
  selector:
    matchLabels:
      app: homer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homer
    spec:
      restartPolicy: Always
      containers:
        - name: homer
          image: b4bz/homer:v24.05.1
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: homer-nfs
            mountPath: /www/assets
          - name: homer-config
            mountPath: /www/assets
      volumes:
        - name: homer-nfs
          hostPath:
            path: /mnt/k3s-data/production/apps/homer/assets/
            type: Directory
        - name: homer-config
          configMap:
            name: homer-configmap