---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nebula-piholes
  namespace: applications
spec:
  encryptedData:
    pihole_primary: AgCfCbk7/mIFZhW1YItPLly6CzXVPFDQWcdED6LNS4TcGn4P1GxO8WKDeGaL38ju4W7EE+8Yj98GkXDn4eG2AiTBuy/aAjR6Kh2R4D+6xmAZ81mvOpNCDbtqbfSmoR5zKUhnu+Sn6eC0TtV57zCm3qnGgxa7yNKwjJ7kup2W2FqRIVw1oAFG8zy2HtWhLECPJDqUQfoRGvQo6/uT+8ByVgBljf6ihIgViiuiiadOx749gTU3YEHiVQATe9yo3WKJoxTUgVkpk2MmgqYwCt1zQ5CbH5Epv+eyavmtGcG9reLgqlCKBWcaleJexEn7SCWPbg49MUSgiRC7ZIWXu5xkWoYtcv2aUMlnB+dPzHOj2ZAPKgwtqqvxBbUKRkdmCd2pPQsnhdfYZkLKArveJbX207parweOqKwp8UlIJUD7TPg7OVsKBa5/VjiyxMBOmWXfViY0jl1lBnMQkWq18wxRd1tlBh6uPQ+X0j9EhKlrYgkS8x/AFz/k7D+SfFDqWz7ZeDtS2fcoI4jgQwJVJ2Dv7iuaiPEdcrb/DFXGqX/wlLTawgoSQ9BAj+kvZn3sbcXncefpx8IOjXW3TGvT5cj90+3xnGCGc9aXVmscuHPomHvU+TOPZmpzY7blc6uVQD7aG32Uftjc2AR7ngf5Q0SQdDLWKAW23R357PlxkP0l8bLMtgb2ZQQbb9rasOGuCNP58quQHkJCo3ZS6BjkXsxNpPOCYhE7t5EbzMlwYdXVP4Ek7AwhF9SIeeRR
    pihole_replicas: AgCqINAcB3X4OUl8SJ6mJ5kgZzuaaS4Rra0MFkz/lPUuyHk1wI4333qD3tnNNbDHykK0l7ZXETcHIWOyIGQ4bbQq9mji08wvVGuK+ONMWK54MSr+62zcoh8L2CAtHduevbDut+96MWwaD0qDPiQvPiZBuZTDzs8EDUTJRpTVixzYviqpZWHnKB11KXfvGcDNOQ8TIgVJ1PhkDHPp3qOhyHNsttjiN6fOJpxjpzlYhUJnIUIXHz2SdBbnuiuJ+Yt12V4gRMpmvBJJa5A6F3G3MGmEoZLT75gkjFkvYGdizeABEspSR8Xw0aoyc9+3zFYG9QkIAiOYuQp5yQA7ZUj4uQosli9EfG6XJV5eRCibzWttBhFEsErz1fX8VbzzfTKqKDBeb2uplirAWsEGcUuROm4CKF1PGlxikrPus98eMHzukBwK4Z52b4ozc0iAokbWEgj/6Tnx/nIjwPi/ZNOxQWeO2hquhIqZTbYTTw/8ufzJpLyQ+K5yLn0RxyCr5+6+DgGM++DGIuwN+1sN2ZXFGmptyMlUzvWFfRbSJUmlw1e+NritcUIqHuIsp1QgbzrVCHZ25BHhi0B/0fhWYE1f6VXodjQroJ/KGF5OL58sC4Ss+ZuzbVMw6tWARIdNCqCcIVLZgo2mFTisytRm2vhodtimsVr+/3jCeJpc2oEFJbTnPqwkrhYwNuW/ZB+8l76wU8zpJm3ZAS+R3nkcAv46C2oDyVOl6zZaAqsKkvCHLOHI65M0w1DWhwrilA==
  template:
    metadata:
      name: nebula-piholes
      namespace: applications
    type: Opaque
