---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nebula-piholes
  namespace: applications
spec:
  encryptedData:
    pihole_primary: AgAhz3zAyntFZ9jrzU1vxwE/RVRtBImY0vjjy2k4e44uR/x9w/0GNoLR4dba6fcK3Lup359ylEQsRp9O1WeOMmNjyAb74QwdZrUUe+9m3XiVR3kmSFK227HHJlhWAz7AacLPUtD09a9VEJkJQTTdiTs1TkzvBR1GBhYDfWBa+gwznzkZOxkVyOUznVxCpy5HrTrhWs9vTonAG0hgPtIurtzDVE3o6K2FLgRPmj/2yldvNygHAEVn30nzubtKJ38weh9XlfQaIBvAPeVPOswnHKJGbgOlAAM+BARxj0yUrPedo0pag77BZYg2sapnwFmu8OTKizPBOJHIatz374NayOBUNxwjRsWKuQsuwEe6Si6Vzaw9vt2Dr75OP+AmvBHU+5oMlfQZNIrTw0UnAOOqzH2w7dxXLG0UAwZho5uF+WCJInIXtGArcU3pTz1pmCA5ErM6OSN7Z+VHyksuBDeTNzAv7qav7Hsa9pHRAazYtFKK+o+U3AJOuoePTZcw5/3iYiaPe/fm3GKgUglRK4cwcpOptYwsi5SxyNUtJ9uI7bNtTG3CK2EpdNEJMddWb1RlhDUBHVx0DTUtjr730LAfdnwbwonbT+I84kHZy0tTB9ojMlecLz6MOVD5gaoRUiq3RQSDJrTtiXmfG3fY17QaycHnV5wy52MNa+MUYg3yO5wa56fiys4TyOSa/k6JsUy3N17TatYwvsjdk1gZt9vXz/XqQGZLmzT5pwWVolgjMMLHboHZGe9PT2IMOzOGIOF8pNpObU0RMhXl4uJbieNfNrpYlm50RTE=
    pihole_replicas: AgAMfx79qG10UQ3MQFr+7DX78w+xGzkcqeex4PaxZ8DTkU0q96j3x0xIZq+OTXV4i5tI2P6FwYHuaQkP2zj5AdXMapV5Oq2+1qVFRCiRq6cicIsexzzxxxm309ziyFmpaun+O7BoOsFd24CkUFOQZouIqvUciUN4HeUBe0sp1o2jomBosgD12GoMbD58Ak+lawf+TcdrnL8v1B5kiqTgcfJW24EAQ4tMYTPEu1245SzJ1ef9vvw2XcWQQD2mCwFeZ/MDzKpggyaa0WZwxYA1JefCMvVRFapArqswTbTFMomvTO9cM8UtBSpa/LIgT/Za+RPdOvMZN86hNPrG8V5h37kmGbFA3D55Z3If+RZAlhh3oaFpGoO3Y5iZ43A7aTMj0JWhW4PgH+K77MjVggT9Sv4gfAZFFKMUhpqH7s+5jFyz8Tt7vDV7zg/jvNZryDblM6tJLDBANSjdGpYHAT93bR4LHL+/GR0xN+O4G9Uw2CturYvR/ErbRSgdarPyA25hmv2QWO2Iof25dpgdJutuZ6quAi9eTyX0mcRJO1JG3XuU3uj6AuAXA//wf33EsTOYtft38daEXdNrD5Do/zB+CCQuH6GE0W5fu7u5MEYVHG9VHBWjIE+BmBA1MEv7MNWeTsbh5855huZrqpKiHxQho7GKuM57a3WECdy8imauRm8bBfXzbaKKmLUwsOlAe0BZsNlZUXhO0FB3NCtsQI3rLcW1I82ARBHUJZal9KdaOpIHY1f1M9XpnUgb0584HzY2cFgtHrbYhA==
  template:
    metadata:
      name: nebula-piholes
      namespace: applications
    type: Opaque
