---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-secret
  namespace: applications
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBRwZUztniDZ/hM0kEuNd2TSiKWsUO78yHc6Bapj7GHGB1QdrpDZBaZFAWcV0xE4XZrjKIPbA7o0Coj8mOkWKY1fYjqqxqSejUSgMo98x3UXVqe5csZccmh2ocX38On9Q1c69cCHaY6NzFVE2ugWpOeRJ6yx7b3KqDPJF+v6+733Kzv+fhU4CO02d3J0JA7b7elENwRjW2hTDUbFXVeWnApKG5MO7ZJGQbHXDk8ZvX1boFsZBOuEcwFyWmRRrp6P/hz2v+j1hPYlAWL1Gk6WUhJRvUidFhTPCk2ANgTmM75kbqMjv2FVE++n14SR6wNZftG9so4+m7naJ3MATERL8WDXS+egglhyPBSlBdWekZHKgPiGqlpPQAs8nM865ktmlpn87hICcU+8mgu7gOGK7sa/OdkNcgnxTGMtcRZxYc04JYSJDegFg9fMBuNxnT6mM1TQyxEJTicsdJoTnvW8PmL5SWpIkmW/yGjXRzbsZEq7elEySYaoEX/87Q6Xuc9dpFE+4Szm3XdlYJZnOy4VpxKtxPjDVEQ7jF3bFyzRrk0QtYPH0v0UzIzPfdSmdArl84sJsO6VTGf3M9szC3QZA0pEYbhVPQzwxFLyAhFCGVq80mPwOXUMxdyulkybeBtPxayjUutnqpG0pnBmRwlqb4Nx7Jb4egbXkM7j42Q1lH2Exi9bhPdJTG9tZHZ5HHqmhAzSZRLD3eZgSLKSUr4LQt1M7nnzA8jY+bT6uLO6Dp78Fs=
    MONGO_PASS: AgBN2hy5JiLVfcVpnsie81q8r41RjewA7sJjidhjeGG69Yh2WXGl2DOGh7UiXgQYqGwXU+RXqtS7HYkwi4MOzxgy6IHYGvcc1LOPC+oI6HumYFlgCRw66T0fDMC7UxXBtlKIWtubtAimhaB6pBTz5haAzqm9RNCvYosAHzJ5J/zIy01t+EWMuuL6qnszxZlneD3INRkXWPEDZniHIwsQUYG6sDpv5UalscKa3EaIFq613tRambFwUMahpTigwczhUaXeaw3X+/AiZOSFkkH5xYBmeIC5wSpOJtzNb7w9wlUsMXQU/Oq4xwzf0fgSwFY9Y4p/qENkXRX60bp2WlgmGa/A8YIynOTFzvXWyVG5fq2ztmsNqLcn8gzjWusGxs0SJqty7Pk720h6JamoIuiGIIzWgjRfictp/tWQFAHZ9qyITm9F5XvLoqEUC62A++AKYXdy9uJHZGCBXY39UxS46SSn1ebiJhlLiEIf4RMKRPFNB5TUg8LyjSsbXwRpJ6A3JuDvOpp4xjK/EDYzOGI2tyHUCd5gGTZ+VDaluaKvnC58cezEBHsTrh6UBxk6HQe9z5+3bYV4n5IoiEsGOetkKNyd5ps84MUxKJbetgX/Vyw9cIWXnc3R3RYhzvtJiZ1ifjD7irEDLOmpvl3M2J9NFpV2TIURI6+hRuuaN6h/pSinblnnzAhPCJArkWnmqJyJy/XEQIs1HRDUshCBWchEtl+Z96aNYx7+jI+t459r2BRsDHk=
  template:
    metadata:
      name: unifi-secret
      namespace: applications
    type: Opaque
