---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-data
  namespace:  lab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
