---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      restartPolicy: Always
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.9@sha256:879f5f35b05566f71296bad0f3704709103568a6b4f42f5959543f5322728723
          resources:
            limits:
              cpu: 4
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 8989
          volumeMounts:
          - name: sonarr-shows-nfs
            mountPath:  /tv
          - name: sonarr-downloads-nfs
            mountPath:  /downloads
          - name: sonarr-config
            mountPath:  /config
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: TZ
            value:  America/New_York
      volumes:
        - name: sonarr-shows-nfs
          hostPath:
            path: /mnt/mobius/Video/TV-shows
            type: Directory
        - name: sonarr-downloads-nfs
          hostPath:
            path: /mnt/mobius/temp/qflood/downloads
            type: Directory
        - name: sonarr-config
          persistentVolumeClaim:
            claimName:  sonarr-config-pvc