---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: CHANGE_ME
  labels:
    app: CHANGE_ME
spec:
  selector:
    matchLabels:
      app: CHANGE_ME
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: CHANGE_ME
    spec:
      restartPolicy: Always
      containers:
        - name: CHANGE_ME
          image: CHANGE_ME
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: CHANGE_ME-nfs
            mountPath: /www/assets
          env:
          - name: key_CHANGE_ME
            value:  value_CHANGE_ME
          - name: env_CHANGE_ME
            valueFrom:
              configMapKeyRef:
                name: env_CHANGE_ME
                key:  key_CHANGE_ME
      volumes:
        - name: CHANGE_ME-nfs
          hostPath:
            path: /mnt/k3s-data/production/apps/CHANGE_ME
            type: Directory
        - name: CHANGE_ME_config_map
          configMap:
            name: CHANGE_ME_config_map
            defaultMode:  0777
        - name: CHANGE_ME_pvc
          persistentVolumeClaim:
            claimName:  CHANGE_ME_pvc
        - name: CHANGE_ME_png
          projected:
            sources:
            - configMap:
                name: CHANGE_ME_png-b
            - configMap:
                name: CHANGE_ME_png-g 