---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
spec:
  selector:
    matchLabels:
      app: homer
  replicas: 2
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: b4bz/homer:latest
          ports:
            - containerPort: 8080
