---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rflood
  labels:
    app: rflood
spec:
  selector:
    matchLabels:
      app: rflood
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rflood
    spec:
      restartPolicy: Always
      containers:
        - name: rflood
          # using "latest" because the versions are something like "release-1f62614"
          image: ghcr.io/hotio/rflood:latest@sha256:761e6d764d6cc9d0e10081d0e66ab2cc89686b2b3e7ed57f489e8ef22eded338
          ports:
            - containerPort: 3000
            - containerPort: 5000
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: UMASK
            value:  "002"
          - name: TZ
            value:  America/New_York
          - name: FLOOD_AUTH
            value:  "false"
          # - name: ARGS
          #   value:  ""
          # - name: FLOOD_ARGS
          #   value:  ""
          # we don't want this built-in wireguard VPN
          - name: VPN_ENABLED
            value:  "false"
          - name: UNBOUND_ENABLED
            value:  "false"
          securityContext:
            capabilities: # Needed for VPN
              add:
                - NET_ADMIN
            privileged: true
          volumeMounts:
          - name: rflood-config
            mountPath:  /config
          - name: rflood-data
            mountPath:  /data
        # - name: openvpn
        #   image: openvpn/openvpn-as
        #   # TODO:
      volumes:
        - name: rflood-config
          persistentVolumeClaim:
            claimName:  rflood-config-pvc
        - name: rflood-data
          persistentVolumeClaim:
            claimName:  rflood-nfs-data-pvc