---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rflood
  labels:
    app: rflood
spec:
  selector:
    matchLabels:
      app: rflood
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rflood
    spec:
      restartPolicy: Always
      hostname: rflood
      subdomain: internal
      containers:
        - name: rflood
          # using "latest" because the versions are something like "release-1f62614"
          image: ghcr.io/hotio/rflood:latest@sha256:761e6d764d6cc9d0e10081d0e66ab2cc89686b2b3e7ed57f489e8ef22eded338
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 3000
            - containerPort: 5000
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: UMASK
            value:  "002"
          - name: TZ
            value:  "America/New_York"
          - name: FLOOD_AUTH
            value:  "false"
          - name: VPN_ENABLED
            value:  "true"
          - name: VPN_CONF
            value:  "wg0"
          # i think by using 192.168.0.0/16, it will allow connection from other VLANs
          - name: VPN_LAN_NETWORK
            value:  "192.168.0.0/16"
          - name: VPN_LAN_LEAK_ENABLED
            value:  "fakse"
          # listed ports will be blocked for VPN, but allowed for local
          # - name: VPN_EXPOSE_PORTS_ON_LAN
          #   value: ""
          - name: VPN_AUTO_PORT_FORWARD
            value:  "true"
          # - name: VPN_AUTO_PORT_FORWARD_TO_PORTS
          #   value: ""
          - name: VPN_KEEP_LOCAL_DNS
            value:  "false"
          - name: VPN_FIREWALL_TYPE
            value:  "auto"
          - name: VPN_HEALTHCHECK_ENABLED
            value:  "true"
          - name: VPN_PIA_USER
            valueFrom:
              secretKeyRef:
                name: pia-vpn-creds
                key: username
          - name: VPN_PIA_PASS
            valueFrom:
              secretKeyRef:
                name: pia-vpn-creds
                key: password
          - name: VPN_PIA_PREFERRED_REGION
            value: "Netherlands"
          - name: VPN_PIA_PORT_FORWARD_PERSIST
            value:  "false"
          - name: PRIVOXY_ENABLED
            value:  "false"
          - name: UNBOUND_ENABLED
            value:  "false"
          securityContext:
            capabilities: # Needed for VPN
              add:
                - NET_ADMIN
            # privileged: true
            # sysctls:
            # - name: net.ipv4.conf.all.src_valid_mark
            #   value:  "1"
            # - name: net.ipv6.conf.all.disable_ipv6
            #   value:  "1"
          volumeMounts:
          - name: rflood-config
            mountPath:  /config
          # - name: rflood-wg0-config-file
          #   mountPath:  /config/wireguard/wg0.conf
          #   subPath:  wg0.conf
          - name: rflood-data
            mountPath:  /data
      volumes:
        - name: rflood-config
          persistentVolumeClaim:
            claimName:  rflood-config-pvc
        - name: rflood-data
          persistentVolumeClaim:
            claimName:  rflood-nfs-data-pvc
        # - name: rflood-wg0-config-file
        #   secret:
        #     secretName: rflood-wg0-config