---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rflood
  labels:
    app: rflood
spec:
  selector:
    matchLabels:
      app: rflood
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rflood
    spec:
      restartPolicy: Always
      hostname: rflood
      subdomain: internal
      initContainers:
      - name: init-rflood-wg0-config
        image: busybox
        command: ["sh", "-c", "mkdir -p /config/wireguard && cp /wireguard/wg0.conf /config/wireguard/wg0.conf"]
        volumeMounts:
        - name: rflood-config
          mountPath:  /config
        - name: rflood-wg0-config-file
          mountPath:  /wireguard
      containers:
        - name: rflood
          # using "latest" because the versions are something like "release-1f62614"
          image: ghcr.io/hotio/rflood:latest@sha256:761e6d764d6cc9d0e10081d0e66ab2cc89686b2b3e7ed57f489e8ef22eded338
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 3000
            - containerPort: 5000
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: UMASK
            value:  "002"
          - name: TZ
            value:  "America/New_York"
          - name: FLOOD_AUTH
            value:  "false"
          - name: VPN_ENABLED
            value:  "true"
          - name: VPN_PROVIDER
            value:  "pia"
          - name: VPN_CONF
            value:  "wg0"
          - name: VPN_LAN_NETWORK
            value:  "192.168.0.0/16"
          - name: VPN_PIA_USER
            valueFrom:
              secretKeyRef:
                name: pia-vpn-creds
                key: username
          - name: VPN_PIA_PASS
            valueFrom:
              secretKeyRef:
                name: pia-vpn-creds
                key: password
          - name: VPN_PIA_PREFERRED_REGION
            value: "nl_amsterdam"
          securityContext:
            capabilities: # Needed for VPN
              add:
                - NET_ADMIN
            # privileged: true
          volumeMounts:
          - name: rflood-config
            mountPath:  /config
          - name: rflood-data
            mountPath:  /data
      volumes:
        - name: rflood-config
          persistentVolumeClaim:
            claimName:  rflood-config-pvc
        - name: rflood-data
          persistentVolumeClaim:
            claimName:  rflood-nfs-data-pvc
        - name: rflood-wg0-config-file
          secret:
            secretName: rflood-wg0-config