---
apiVersion: v1
kind: Service
metadata:
  name: rflood
  annotations:
    metallb.universe.tf/allow-shared-ip: "rflood-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: rflood
  ports:
    - name: flood
      port: 3000
      targetPort: 3000
    - name: rtorrent
      port: 5000
      targetPort: 5000
  type: LoadBalancer