---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  annotations:
    metallb.universe.tf/allow-shared-ip: "radarr-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: radarr
  ports:
    - name: radarr-ui
      port: 7878
      targetPort: 7878
  type: LoadBalancer