libraries:
  Movies:
    remove_overlays: false
    overlay_files:
      - default: resolution
      - default: languages
      - default: ratings
        template_variables:
          rating1: user
          rating1_image: rt_tomato
          rating1_font_size: 63
          rating2: critic
          rating2_image: imdb
          rating2_font_size: 70
          rating3: audience
          rating3_image: tmdb
          rating3_font_size: 70
          horizontal_position: right
      - default: runtimes
      - default: video_format
      
  TV Shows:
    remove_overlays: false
    overlay_files:
      - default: ratings
      - default: resolution
      - default: status

settings:
  cache: true
  cache_expiration: 60
  asset_directory: /config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: true
  show_missing_episode_assets: true
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: true
  custom_repo:
  check_nightly: false
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:

plex:
  url: http://192.168.12.2:32400
  token:  <<PLEX_TOKEN>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
  db_cache: 4096
  verify_ssl: false

tmdb:
  apikey: <<TMDB_KEY>>
  language: en
  cache_expiration: 60
  region: US

radarr:
  url: http://192.168.13.32:7878
  token: <<RADARR_TOKEN>>
  add_missing: true
  add_existing: false
  root_folder_path: /movies
  monitor: true
  availability: announced
  quality_profile: HQ
  search: true
  upgrade_existing: false
  ignore_cache: false
  monitor_existing: false
  tag:
  radarr_path:
  plex_path:

sonarr:
  url: http://192.168.13.33:8989
  token:  <<SONARR_TOKEN>>
  add_missing: false
  add_existing: false
  root_folder_path: /tv
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  search: true
  cutoff_search: true
  upgrade_existing: false
  monitor_existing: false
  ignore_cache: false
  tag:
  sonarr_path:
  plex_path:
