- name: deploy git repo to single DEV Swarm worker
  hosts:  k3s_data
  tasks:

    - name: deploy dev_test branch
      git:
        repo: "https://github.com/educatedCaveman/k3s_lab"
        dest: "/mnt/k3s-data/{{ dir }}"
        version:  "{{ branch }}"
        force:  yes

    - name: repo permissions
      file:
        path:     "/mnt/k3s-data/{{ dir }}"
        state:    directory
        recurse:  yes
        owner:    nobody
        group:    nogroup
        mode:     '1777'
