pipeline {
    agent any 

    environment {
        WEBHOOK = credentials('JENKINS_DISCORD')
        APP_NAME = 'jellyfin'
    }

    //triggering periodically so the code is always present
    // run every friday at 3AM
    triggers { cron('0 3 * * 5') }

    stages {
        // PRD
        stage('PRD: Apply Kustomization') {
            when { branch 'master' }
            steps {
                sh 'kubectl apply -k ${WORKSPACE}/apps/${APP_NAME}/overlays/prd/'
                // sh 'kubectl apply -k ${WORKSPACE}/apps/${APP_NAME}/overlays/prd/ --prune -l app=${APP_NAME} -n prd'
            }
        }

    }
    post {
        always {
            discordSend \
                description: "${JOB_NAME} - build #${BUILD_NUMBER}", \
                result: currentBuild.currentResult, \
                webhookURL: "${WEBHOOK}"
        }
    }
}

