---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-test

# insert a separate file as a configmap
configMapGenerator:
# encoding.xml
- name: jf-encoding-configmap
  files:
  - encoding.xml
# network.xml
- name: jf-network-configmap
  files:
  - network.xml
# system.xml
- name: jf-system-configmap
  files:
  - system.xml
# # movie_options.xml
# - name: jf-movie-opts-configmap
#   files:
#   - media/movies/options.xml
# # music_options.xml
# - name: jf-music-opts-configmap
#   files:
#   - media/music/options.xml
# # shows_options.xml
# - name: jf-show-opts-configmap
#   files:
#   - media/shows/options.xml

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: jellyfin

resources:
- ../../base

namePrefix: dev-

patches:
- path: svc_IP.yml
# - path: volumes.yml
