---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  template:
    spec:
      volumes:
        - name: jf-config-nfs
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/kustomize/jellyfin/config
