---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tesseract-env
  namespace:  bots
data:
  IDRAC_PASSWORD: <redacted>
  FAN_SPEED: "20"
  CPU_TEMPERATURE_THRESHOLD: "auto"
  CPU_TEMPERATURE_SOURCE: "auto"
  CHECK_INTERVAL: "1m"
  MAXIMUM_IPMI_UNREACHABLE_DURATION: "5m"
  MAXIMUM_CONSECUTIVE_IPMI_FAILURES: ""
  DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE: "true"
  KEEP_THIRD_PARTY_PCIE_CARD_COOLING_RESPONSE_STATE_ON_EXIT: "true"
  MONITORING_ONLY_MODE: "false"