---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace:  applications
  labels:
    app: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      topologySpreadConstraints:
        - maxSkew:  1
          topologyKey:  kubernetes.io/hostname
          whenUnsatisfiable:  ScheduleAnyway
          labelSelector:
            matchLabels:
              app: pihole
      restartPolicy: Always
      containers:
        - name: pihole
          image: pihole/pihole:2025.04.0@sha256:c2215c570976ebc23ab6688f556a80133d4236dae0bffee678129da4396fbd61
          resources:
            limits:
              cpu: 4
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 50Mi
          env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: pihole-env
                key:  TZ
          - name: FTLCONF_dns_listeningMode
            valueFrom:
              configMapKeyRef:
                name: pihole-env
                key:  FTLCONF_dns_listeningMode
          - name: FTLCONF_webserver_api_password
            valueFrom:
              secretKeyRef:
                name: pihole-pass
                key:  FTLCONF_webserver_api_password
          ports:
            - containerPort: 53
              name: pihole-dns-tcp
              protocol: TCP
            - containerPort: 53
              name: pihole-dns-udp
              protocol: UDP
            - containerPort: 80
              name: pihole-http
              protocol: TCP
            - containerPort: 443
              name: pihole-https
              protocol: TCP
          volumeMounts:
          - name: etc-pihole
            mountPath:  /etc/pihole
      volumes:
        - name: etc-pihole
          persistentVolumeClaim:
            claimName:  pihole-pvc