pipeline {
    agent any 

    environment {
        WEBHOOK = credentials('JENKINS_DISCORD')
        APP_NS = 'applications'
        APP_NAME = 'pihole'
    }

    //triggering periodically so the code is always present
    // run every friday at 3AM
    triggers { cron('0 3 * * 5') }

    stages {
        stage('deploy') {
            when { branch 'master' }
            steps {
                sh 'kubectl apply -k ${WORKSPACE}/apps/${APP_NS}/${APP_NAME}'
            }
        }
    }
    post {
        always {
            when { branch 'master' }
            discordSend \
                description: "${JOB_NAME} - build #${BUILD_NUMBER}", \
                result: currentBuild.currentResult, \
                webhookURL: "${WEBHOOK}"
        }
    }
}

