---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace:  applications
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: pihole
  ports:
    - name: pihole-dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: pihole-dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: pihole-http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: pihole-https
      port: 443
      targetPort: 443
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 192.168.13.236