---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secrets
  namespace: applications
spec:
  encryptedData:
    bazarr_api_key: AgByfMR8Q+Z3yd4r4q7auTdB5nYL4cYgEMzcYcrzIxwRxemdvtaItcXFdQWd1tBi4RTkwFxVKLgBfDFofw0cjlIsuQQTW9wCfPJnAxl9ANR6E/lk3JR5+EoiXKMVkmatP2NI5C+0UbyoCS1iXNHYQOrOuy75DAXW52+/PMy+VoouaessH2VeGbvlKvS/GvfvfNpiiGwaouyYVhROGdNR08w1zqQCWPBxicPx2x8h6+8iAksxRZhjDk8zHsk/Dl6LnOsL61MUDgoVdZREtEFrFWsv+WzoDfRWObNH3QveEqSrzFN0UZ1tetU5naxVA1e8ITNGVICX9KBhCgph5WpwAFS/CkyONVY/TvlHlsErZhxohfy4IY1w1nJb77wAi1i3xuxpog8NX9E4simapCh2+ZTxZuA94/t+jnSOWjn4+WPJZs61SkjETfb0C8Na6lY3LLij+omjJiX3tsY76evExYiIiqX93DXSpLsZpvu20hMuI2WpKsLhsY0V373IPuLQRU4c3FG879OpbvHv1LhY5vTvTulVueI4lB6hJv5Yy91WGOnSuTquq8hxmPuiFw5/KphS9aqfbDrh4czTkpvC3UpRfXQB0OQQ9AU/yfKudGL7/INt4SAu5+4oHIU1DEaCmsfEkspOYZ4OtAxRxESVgn6FIRL2UAWg2pem3Q2hGBA+DD6bA/w27mjtLqW0JqJDkdtojXdST3CTR0G9hNW7rucgi7PXqRkfQGJLd1bHzAfg4w==
  template:
    metadata:
      name: homepage-secrets
      namespace: applications
    type: Opaque
