---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  annotations:
    metallb.universe.tf/allow-shared-ip: "flaresolverr-metallb-ip"  
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: flaresolverr
  ports:
    - port: 8191
      targetPort: 8191
  type: LoadBalancer