---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr 
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: flaresolverr
  ports:
    - port: 8191
      targetPort: 8191
  type: LoadBalancer