---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-config-data
  namespace:  media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model-data
  namespace:  media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
