---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace:  media
  annotations:
    metallb.universe.tf/allow-shared-ip: "whisper-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: whisper
  ports:
    - name: whisper
      port: 9000
      targetPort: 9000
  type: LoadBalancer
  loadBalancerIP: 192.168.13.39