---
apiVersion: v1
kind: Service
metadata:
  name: plex-meta-mgr 
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: plex-meta-mgr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-meta-mgr
  labels:
    app: plex-meta-mgr
spec:
  selector:
    matchLabels:
      app: plex-meta-mgr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex-meta-mgr
    spec:
      restartPolicy: Always
      containers:
        - name: plex-meta-mgr
          image: meisnate12/plex-meta-manager:v1.19.1
          volumeMounts:
          - name: CHANGE_ME-nfs
            mountPath: /www/assets
      volumes:
        - name: plex-meta-mgr-nfs
          hostPath:
            path: /mnt/k3s-data/production/apps/pmm/config
            type: Directory
