---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
spec:
  selector:
    matchLabels:
      app: homer
  replicas: 1
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: b4bz/homer:latest
          ports:
            - containerPort: 8080
      #     volumeMounts:
      #     - name: homer-pvc
      #       mountPath: /www/assets
      # volumes:
      #   - name: homer-pvc
      #     persistentVolumeClaim:
      #       claimName: homer-longhorn-pvc