---
apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: homer
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.13.32