---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privateer
spec:
  template:
    spec:
      volumes:
        - name: privateer-nfs-config-radarr
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/privateer/config/radarr
        - name: privateer-nfs-config-sonarr
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/privateer/config/sonarr