---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      restartPolicy: Always
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:2021.12.16@sha256:983e3cf314deaa76b0aa58c82d59c285b2ac2a3ef2f316b0361cb4c8bb58b79d
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 1
              memory: 512Mi
          ports:
            - containerPort: 8096
          volumeMounts:
          - name: jf-movies
            mountPath:  /Movies
          - name: jf-shows
            mountPath:  /TV
          - name: jf-music
            mountPath:  /Music
          - name: jf-config
            mountPath:  /config
          env:
          - name: jf-puid
            valueFrom:
              configMapKeyRef:
                name: jf-env
                key:  PUID
          - name: jf-pgid
            valueFrom:
              configMapKeyRef:
                name: jf-env
                key:  PGID
          - name: jf-tz
            valueFrom:
              configMapKeyRef:
                name: jf-env
                key:  TZ
      volumes:
      - name: jf-movies
        hostPath:
          path: /mnt/mobius/Video/Movies
      - name: jf-shows
        hostPath:
          path: /mnt/mobius/Video/TV-shows
      - name: jf-music
        hostPath:
          path: /mnt/mobius/Music/library
      - name: jf-config
        persistentVolumeClaim:
          claimName:  jf-config-data
          