---
# Arrs: https://wiki.servarr.com/
version: "3"
services:

  # other containers removed from this initial compose file
  # also, changed the version tag to latest to appease renovate

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    # image: lscr.io/linuxserver/prowlarr:1.10.5.4116-ls44
    # image: lscr.io/linuxserver/prowlarr:latest
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/prowlarr:/config
    restart: unless-stopped
    ports: 
      - 9696:9696