---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

# insert a separate file as a configmap
configMapGenerator:
- name: qflood-qbt-configmap
  files:
  - qBittorrent.conf

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: qflood

resources:
  - sealed-secret-pia-vpn-creds.yml
  - sealed-secret-pia-wg0-conf.yml
  - deployment.yml
  - service.yml
  - pv.yml
  - pvc.yml