---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qflood-config-pvc
  namespace:  media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qflood-nfs-data-pvc
  namespace:  media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 500Gi
  volumeName: qflood-nfs-pv