pipeline {
    agent any 

    environment {
        WEBHOOK = credentials('JENKINS_DISCORD')
        APP_NAME = 'nginx-testing'
    }

    //triggering periodically so the code is always present
    // run every friday at 3AM
    triggers { cron('0 3 * * 5') }

    stages {
        // DEV
        stage('DEV: deploy code/configs') {
            when { branch 'dev_test' }
            steps {
                sh 'ansible-playbook deploy.yml --extra-vars "branch=dev_test dir=dev-test"'
            }
        }
        stage('DEV: Apply Kustomization') {
            when { branch 'dev_test' }
            steps {
                sh 'kubectl apply -k ${WORKSPACE}/apps/kustomize/${APP_NAME}/overlays/dev/'
            }
        }

        // PRD
        stage('PRD: deploy code/configs') {
            when { branch 'master' }
            steps {
                sh 'ansible-playbook deploy.yml --extra-vars "branch=master dir=production"'
            }
        }
        stage('PRD: Apply Kustomization') {
            when { branch 'master' }
            steps {
                sh 'kubectl apply -k ${WORKSPACE}/apps/kustomize/${APP_NAME}/overlays/prd/'
            }
        }

    }
    post {
        always {
            discordSend \
                description: "${JOB_NAME} - build #${BUILD_NUMBER}", \
                result: currentBuild.currentResult, \
                webhookURL: "${WEBHOOK}"
        }
    }
}

