---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  annotations:
    metallb.universe.tf/allow-shared-ip: "bazarr-metallb-ip"  
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: bazarr
  ports:
    - name: bazarr-ui
      port: 6767
      targetPort: 6767
  type: LoadBalancer