---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  annotations:
    metallb.universe.tf/allow-shared-ip: "syncthing-metallb-ip"  
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: syncthing
  ports:
    - port: 8384
      targetPort: 8384
      protocol: TCP

    # - port: 22000
    #   targetPort: 22000
    #   protocol: TCP
      
    # - port: 22000
    #   targetPort: 22000
    #   protocol: UDP
      
    # - port: 21027
    #   targetPort: 21027
    #   protocol: UDP
      
  type: LoadBalancer