---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd

# insert a separate file as a configmap
configMapGenerator:
- name: qflood-qbt-configmap
  files:
  - qBittorrent.conf

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: qflood

resources:
- ../../base

namePrefix: prd-

patches:
- path: svc_IP.yml
