---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-meta-mgr
  labels:
    app: plex-meta-mgr
spec:
  selector:
    matchLabels:
      app: plex-meta-mgr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex-meta-mgr
    spec:
      restartPolicy: Always
      containers:
        - name: plex-meta-mgr
          image: meisnate12/plex-meta-manager:v1.21.0
          volumeMounts:
          - name: plex-meta-mgr-nfs
            mountPath: /config
      volumes:
        - name: plex-meta-mgr-nfs
          hostPath:
            path: /mnt/k3s-data/production/apps/pmm
            type: Directory
