---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd

# insert a separate file as a configmap
configMapGenerator:
- name: kometa-configmap
  files:
  - config.yml

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: kometa

resources:
- ../../base

namePrefix: prd-
