---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      restartPolicy: Always
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:10.9.8ubu2204-ls24
          ports:
            - containerPort: 8096
          volumeMounts:
          - name: jf-video-nfs
            mountPath: /mnt/Video
          - name: jf-music-nfs
            mountPath: /mnt/Music
          - name: jf-config-nfs
            mountPath: /config
      volumes:
        - name: jf-video-nfs
          hostPath:
            path: /mnt/mobius/Video
            type: Directory
        - name: jf-music-nfs
          hostPath:
            path: /mnt/mobius/Music/library
            type: Directory
        - name: jf-config-nfs
          hostPath:
            path: /mnt/mobius/Music/library
            type: Directory