---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: "jellyfin-metallb-ip"  
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: jellyfin
  ports:
    - port: 8096
      targetPort: 8096
  type: LoadBalancer