---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgB0dGbwyZClRyeXUH5NhKoVN16cTtz+lC0fedagld7X68vIH8mYjxR6QNbVZYM+YKOmFS8ZagPZuaK1ubMu+t98lvmirKrZ6/Zt9XtQ5mFa1+696Qd+wOGVi79ULvbRXvru6EebQ5oOISvK+X8aUQ2AA/RSi2i2g8tiQGAb5L4EWaz6fvSTDG3gEmkQh5J3OzmmPXPl8kUABbMvZdHIT9yVm7DJQDs8d4IbOBp9Cd94NeCQAjyCss5+VpMGDVxtdBjK0knearXrt09nv2UHuW2GbXubSnVmjguyClh2/zNwDv2jZZxqlNlkV+JGlKw1TupCa39mS275lIvqJ77p35pierWIcNmLDybGd8EwNqenyqyH4kBGExu6+HdWsHgnUUCFR+WC/QnG6QG6bVs167JGfZT8shxQGlSNlNGGGnk3f4VOi3kT4jXD8DDoempSxGnCRK+Cjjkv39H7wiWe/t7pJtwmBIc6cLRyUI+U+IqrWqpkhjMT6CnxvC3U/v/0zhxOJ01e0BPTgdYqBpyaHtcHXOxArGbfynQN8j2GiovKFvS8e1Z3+wouVVwY/KC/OlXr5BtTtOSScTOpAP745DuMP3posGv/SMTiZ/6Q7cAY4rz46/rM8OPFT7x157YzCWo/IGeEVpQDPze74ABgqkdjFoBcyIRFjVV3L+Gcn447EAE4ON7COeBRmN9qHD/1tuZhA+kOnoS9JIjvQKqAfB8=
    username: AgAt9CWC2ao4vJZ1lWiSDQljnquBWyPoab4wLBvM9A8nY4abyslgCYkME7g+QNN0jjMKbBDWpCOsCclldMhcW3UFVEl0ez6XLNyqovTbQdp9/+M1oZmzlUAxtm/s6H6ffjBDaHmzsNcR/FvrWBjhCY5GS+bv/3VWy+ZlVtOt+E2SVYDMbIbsud7tc9E6vB/KwIu60EnpKiySXrZZAG+RagUoHhjX900yOF2NopXzkNSoCvx8VJl2us04GABuge0fk5sup/aA2rOfNa02STv2CUwoUKA6IRIskrYCYs3wAoGnwwZLpWYqTTl9tMZ9vzRPYpu8evgkf07gjYB8WC1AZcmDLqu4c3nE1jfkxYH5yO7/Dudxq1GfFnNWn6ed6GpdIY71xk+QgRrutl+xEOcKNWac5gdFFqCzKdMYEXH8xz99lR3ai9XlmOOURZzwo7i7cH3/mlHGr3SbnNuM7L2kWdL6SCc+GQ3UmJUHLHfPQZ58F702PJ33DGzusoGpjVZxeYmX8HrdI9x76SuwOI43TleJcw5uoIZ1UuiYkXaC1MSZjepk3cD1SrhMvYsng+LfLsW+EC3RXFI+8Ht5QNL7uUUGa9WAP4xrKm98g2VCN8tPwixZCW82fv/jssuDr9T0Q1QCPjI26peVZ2/hctI5FL7rWkn23XNBRIaVcYDfNt3dJqVWCuEKWz7WLCz9kRR+28ZP6G+1btbBM/uJ/Lqw3qk=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
