---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd

# insert a separate file as a configmap
configMapGenerator:
- name: unifi-mongo-init-configmap
  files:
  - init-mongo.js

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: unifi

resources:
- ../../base

# namePrefix: prd-

patches:
- path: svc_IP.yml
