---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  labels:
    app: lidarr
spec:
  selector:
    matchLabels:
      app: lidarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      restartPolicy: Always
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:2.4.3.4248-ls6@sha256:e504ab630ab456a4a39a6801f760975ff84fe53a0e542439d80aa8da27773a6e
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 8686
          volumeMounts:
          - name: lidarr-music-nfs
            mountPath:  /music
          - name: lidarr-downloads-nfs
            mountPath:  /downloads
          - name: lidarr-config
            mountPath:  /config
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: TZ
            value:  America/New_York
      volumes:
        - name: lidarr-music-nfs
          hostPath:
            path: /mnt/mobius/Music/library
            type: Directory
        - name: lidarr-downloads-nfs
          hostPath:
            path: /mnt/mobius/temp/transmission
            type: Directory
        - name: lidarr-config
          persistentVolumeClaim:
            claimName:  lidarr-config-pvc