---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  selector:
    matchLabels:
      app: syncthing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      restartPolicy: Always
      containers:
        - name: syncthing
          image: lscr.io/linuxserver/syncthing:1.27.2
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: TZ
            value:  America/New_York          
          ports:
            - containerPort: 8080
            - containerPort: 22000
            - containerPort: 21027
          volumeMounts:
          - name: syncthing-docs-nfs
            mountPath: /Documents
          - name: syncthing-pics-nfs
            mountPath: /Pictures
          - name: syncthing-music-nfs
            mountPath: /Music
          - name: syncthing-config
            mountPath:  /config
      volumes:
        - name: syncthing-docs-nfs
          hostPath:
            path: /mnt/mobius/Documents
            type: Directory
        - name: syncthing-pics-nfs
          hostPath:
            path: /mnt/mobius/Pictures
            type: Directory
        - name: syncthing-music-nfs
          hostPath:
            path: /mnt/mobius/Music
            type: Directory
        - name: syncthing-config
          persistenVolumeClaim:
            claimName:  sync-config-pvc