---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: "bazarr-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: bazarr
  ports:
    - name: bazarr-ui
      port: 6767
      targetPort: 6767
  type: LoadBalancer
  loadBalancerIP: 192.168.13.35