---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-cache
  namespace:  applications
  labels:
    app: apt-cache
spec:
  selector:
    matchLabels:
      app: apt-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apt-cache
    spec:
      restartPolicy: Always
      containers:
        - name: apt-cache
          image: sameersbn/apt-cacher-ng:latest@sha256:6d612ae08493af17eb5682cf0b29d75c18fd6455e786239fa63fe56ebca552fa
          ports:
            - containerPort: 3142
          volumeMounts:
          - name: apt-cache-data
            mountPath: /var/cache/apt-cacher-ng
      volumes:
        - name: apt-cache-data
          persistentVolumeClaim:
            claimName:  apt-cache-pvc