---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apt-cache-pvc
  namespace:  applications
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
