---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

# insert a separate file as a configmap
configMapGenerator:
- name: jf-baseconfig-configmap
  files:
  - system.xml

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: jellyfin

resources:
- ../../base

namePrefix: dev-

patches:
# - path: pvc.yml
- path: svc_IP.yml
