---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

# insert a separate file as a configmap
configMapGenerator:
- name: jf-system-xml-configmap
  files:
  - configs/system.xml
- name: jf-encoding-xml-configmap
  files:
  - configs/encoding.xml
- name: jf-migrations-xml-configmap
  files:
  - configs/migrations.xml
- name: jf-network-xml-configmap
  files:
  - configs/network.xml
- name: jf-movie-xml-configmap
  files:
  - configs/movie-options.xml
- name: jf-music-xml-configmap
  files:
  - configs/music-options.xml
- name: jf-show-xml-configmap
  files:
  - configs/show-options.xml

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: jellyfin

resources:
- ../../base

namePrefix: dev-

patches:
- path: svc_IP.yml
