---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

# # insert a separate file as a configmap
# configMapGenerator:
# - name: CHANGE_ME-configmap
#   files:
#   - config.yml

# # needed for pruning in the Jenkinsfile
# generatorOptions:
#   labels:
#     app: CHANGE_ME

resources:
- ../../base

namePrefix: dev-

patches:
- path: pvc.yml
- path: svc_IP.yml
