---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace:  media
  annotations:
    metallb.universe.tf/allow-shared-ip: "sonarr-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: sonarr
  ports:
    - name: sonarr-ui
      port: 8989
      targetPort: 8989
  type: LoadBalancer
  loadBalancerIP: 192.168.13.33