---
apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace:  applications
  annotations:
    metallb.universe.tf/allow-shared-ip: "homer-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: homer
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.13.27