---
title: "Grand Ol' Dungeon of the Horned God"
description: "Homelab Homepage"
# my refered default theme and colorscheme,
# but i dont want to disable the option to chage them
# theme: light
# color: neutral
# TODO: longhorn
useEqualHeights: true
background: 
  image:  https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/SMPTE_Color_Bars.svg/3840px-SMPTE_Color_Bars.svg.png
  opacity:  50
  # use these
  blur: xl
  brightness: 50
  saturate: 100
  # XOR these
  # cardBlur: 3xl
layout:

  Links:
    header: false
    style:  row
    columns:  8

  Servers:
    style:  row
    columns: 3

  Remote Management:
    header: false
    style:  row
    columns: 3

  Media:
    style:  row
    columns:  4

  Torrents:
    style:  row
    columns:  3

  group 1:
    Syncthing:
      style:  row
      columns:  2
    Hu3bert:
      style:  row
      columns:  2
    Unifi:
      style:  row
      columns:  2

  Monitoring & Admin:
    style:  row
    columns:  4

  # DNS:
  #   style:  row
  #   columns:  1
  # DNS_nodes:
  #   header: false
  #   style:  row
  #   columns:  4

  Syncthing:
    style:  row
    columns:  2

  Hu3bert:
    style:  row
    columns:  2

  group_2:
    Development:
      style:  row
      columns:  2

    Home Assistant:
      style:  row
      columns:  2