---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-pia-vpn-creds
  namespace: media
spec:
  encryptedData:
    password: AgA3SZK1axeqyBPCqgtp9mI0xChCUy/AGRKTpceGybG2q/O4o9psG6kEgO0R4I4K8MmcD564nnjE2AhHUFzXi7oZOElcnYv8qEGFx0bYGt9ESH9pH7h/2vvo+tfwh97KzC+C4GfaDkIENC7EbUCezuN4wCysQeFdxPBHAjbF4J7qITVPSIooVtJ0JBmI6r4UeCTtTrNjlzvUHIAuyGgmMINElFH9Ud63L1It9waDRP0uM8ODX9ocPy3xpB7ueWsdYC5x3cxoY3hYwTC1jKHe7PQ9vYc6IzzJtyarOgaLoueyhkeYI0LH5O6F45yMwIyeZsfTHOO6v4yros86k1uV2h8XxhpM00Ln/hDqhx2VNCMc/W23kJT/twA6y6bxCcGrKy5vP0l7MjSt4SN8Hr/wCz03rJFv7+KWnQ5/DRzzgoTFw9s/+fVKf98d/OfIeDML4R/sJE6TJj5jPl0WJ9tZ2CR2n3ZumbYoxWd3CkBtA4DzweieFRtLy3J0EW3wisv+eDKs6SPOq+0bb0f6rtxCQUkifDdgFGkko0ebl/BCHgHir2y+WTHyyjyLXJ8c5Ig3ocenpF6IwTnrHOxx6mU5cQTgdkdrK/mjuVEBrXLF81tEM4m7lxfYY8jNCSzWBGZ07aKS/WgCpFZFVXQMPjeVhFPgEP9qMyGP4RkkPqFYW/cwzc5rEstMvtk71kGoUbuZtTUpZyb/T5yW/fewJA==
    username: AgBuMjMIC7KHCit5FAogM0j2jdjRZXNkQaN4ndvlwYitVED7SWMffBQBa5Z6RmIoO0oIfU619ya/q3v5YLbEStYZfWXLxWtnOvKpJRbRvIhfQwPWJrCVG0AZUZPOMu4TW465Hx9hUVNP09ky+52jdnrWpCpyW1/7Fi/Wk2E6cxYKWnzXGgmWCFaFs39r/NdFaGTnkAXNcDe6Mrz8FIlLhu2rfQQDWc7ZfbA2qMMYkOgzRB71IFmFQqbNqiH/bWonmwCCxHZaFwIqquZOHJnfkKwkYkeKV5jI0cA4stvwznDfe9CwwRmumVoYd4u86zMGIXJONJTFqxuHlq82cre6vibWI6rgi4sR9irohG55H0y8K6YDh+yGwC34H5o5ibFTQ9q6zEPkpLuVQwKYF3P9VqwFkYpSKq1eYdtIZmT33X1r07/hpAlur/I/A4cP95D2XLQc0gdIraSmPCPEIFlBRyO8Vj3g1TihTOKIHX//U6yF4hpEm1swdPBTVF5TpR+IsRozNPGoYjlZEFFRT3lETrgUTn+NEv9SH0Jh9hxzMemHYkx05pDCtLO/9gOOjdyPrV2NpFavglT4kR8M5VHDN1q2vb1+YhdZMC/bn76uO8xrXHGZtKnJWWrVLJeZiWLo40W7NDFp5emUVxNZqHOIPwWIrhNyjP2HtHZx+BacKuGWa+vbx4BFq4+GAChE4LGl0p2TsnsGc0dKOOY=
  template:
    metadata:
      name: qbittorrent-pia-vpn-creds
      namespace: media
    type: Opaque
