---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-pia-vpn-creds
  namespace: media
spec:
  encryptedData:
    password: AgB1SpBDgIkoMFoWvvKC9nSvhNpFyOVyV5Hy2s3Pmf+z12buaEDG1JI0zhDrHZPU268MVMn84BY4Et+w+nv5OPny8hGOtVjtAmsXqWMF8Caq5JiZQW/RUaNPPy7p6doyGyR0q+L6xosdcZ6qgpANrm6V+vLmghJlUWAjQ3fY026XmMnzUc/BiwK/HdNzubrp3hlbQchDsPkp6RHxWAj4ghvMslAwu8SphnzLAg+AHEZ7Ah6wZL3Pc80jg0ob+nkucx+0pNzmt8jO5oSMeIo6GIrHAPNEqc5ncg9Gwsb+d1rkBgL8QNIdJKQlwmeNosFMfXj2J0iq6QDguJM7fb0f8/mbMjaaP2xEtRQfZtLLBIXFK2yJFRX2Xc5SXrmfM8DI+awoR1Vspk3douvQ9qDteldljzFmndCBOUCAjPTg5p0vDAGyQ1ZBanhnge6ChX3p9VT0S+PW1HTM6p4Zdmv1RitvVZL0Uzs6GY/Wmfq7KEmxR2KwxyOi4RBLm/0/i0wOfFm1IOHCgRxtIq1WOZKJ6qocjklkylxM5y488FeJc6plNEQY88y/g/AqfvbmmBOKFFJT1VrjNpGHwjSVpAt4UZNQwPDYqlVy/XaLCPhkM9p2ZeUlS+8L1KDwtAm6xGoOWnnfT8jLPGcGgKEFaYLZWanXLubfCwA5ga0y1RwErojnwf/1kXez6U5BwJMzCgn+41QnwHQTk85R8sPRyeJbzdv0jnoWUvk1Mb9eBGq1gOdtkw==
    username: AgA2ROPTx4izeypsX/Y+hW/jZ7akH0QZNXU1R9yQTn0ngiWXJBElvhMAzx+r+QPxYQXXsxun3tipFw7qhKG0cz4MOU7ULvONVhJuwF6v6bseE9noXpaeCagaPf4PZpr339ZnE/2n7O18E6qhpjCJyfyIUlK6iMuIpmqoniScn5AyNioIOe0k7Tw6JJ/qmlEFx0PP29jNO1o917VxOriC8BN1hHnbiqX+rlNhOejpls6mgCPBjzrOON+y1eaMpAPHe0Eyx3kZW511w/RtLhEGt4sdqjHztyt9Wg8o56kX6fuv2A6fCU9PPKngmT/hTegEEmDlfd0qEIf3CwqRMAuwFTCwr2mVS53NBiBG2Y2yaGbx2wX9XHu6GJHx38/hsTrgBn0DOSF0cVjT/aXDKlEaG1n8iuk8N35UjlxIMtO4TZocdGm/lCNs52yBgdJNMH/LjpZKvisTD21zN61ZktO5Q5EmigUSUMMV4mHkgB6ssEWf8ma+NWx3HY7c+HKX4LySMSHJLR1nDCaPAoM5kq8FJ9QAb6eQcqyacVdU5/TnfAh5lyTPG8qXJQUKv/j8G6EOa8Rdw6impMa6iqlmkvLIZoMcKVBcNn1NsDvGAKpLMKFE7WtmmnoGZD+exxoGoof6z5dht4v02MKrr+HxAr02n55T3XXjjtZr+AKjdsQHLvwXmEWHAbx6PThw3JPJcsDjdTZITFQf/xKNUg==
  template:
    metadata:
      name: qbittorrent-pia-vpn-creds
      namespace: media
    type: Opaque
