---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-pia-vpn-creds
  namespace: media
spec:
  encryptedData:
    password: AgAEzLw4rkvlyIhCWyZXNVpcERBfVeCdn17dBKQrcmXWehNTduwitcnOkZn4eTrp3x5dqzvn7NfpDnUHslSROXMd0JWSa4d/ne1ek83h7z4H28ncONGBORdsZjbuePcu+bSP5ZnCo16lTEOeQMWU1pz5jqIxZIJrIuwUNu6M7WN2VrEEzl0N+1qB7ZfF5HAjEXw0CWPJgUJE8y51x8UegK1syIoZRHrJhHo9bTeX8hjSHFNHhE0c8gsaex/p+CGSa7hMfdyDc2R4209Ngu2xk9XYNg9tHeH8Q4a6L91zFyF5xYbv31Jz45rWCJki+S8o0ewCh7NEH/yKzvE/bn33aKyXVn7wQWwT+cHVWjWN5wCnMWCPvcu04+q2amKFuoNp9fWXHA3ftB+xr8UAiv3PFvKRz4/LoLS5n9PYRRXUyWy+AvPDZYJuNE/VtY5wm53yz1C7eRb2nNAOZn1V7E6CRxIdIRZ0kdJDCZa8VpHfVZ1Xezi+d8Vnj/Uw/5vQz0sRB7ch4Z760v7cgYrCHl3s3YlIqj0nos/wDwwNagxO40zcUoahXOicDjh66mtcQBLX68WuY7FnOtuH7jUinLjYY3jtPX6tVklrqEAo06zGmIDeTGDmYzR5vbX808Id2lc7KTGox/uhw0AplaPZ9blmns3N7JHjnWl2kQKXe1VPUn4cwiXxRNjS3AjVm8JRy/rG4/6Ba7Ls/Q3ukAMTe0zOH2fIC0NJq6YSZUDjtMCSoBqNSsA=
    username: AgBnuFlcTk4RfWv6YM1q7Jj+MPO8n+uS0izaEcW9yD/G70xYJqPNT9WFXRraCIL6nMNDBQjZom1t2BtnlB8Tq5xBYPLiJ0rXqGUNIZ+fWS1y8rlVozv4mnXkAloS5Kprp0Ay3T2wbSGi5O+EX5we+0/nbuiqNfyWq1IZyPzXrcSp4AE2u6dsogOKrgaZWywPHUiidwhMG39hpdZ9RJxeJcB0Yx4kEbFZb1PpCTSk0GPfSCitMUoGoa4zICMwoDYz+jkgXxpmDRce/e+PF+N+tSQDRdp25yLHpXydmX92Gdcnxr37ysAJRLrnd+BiclV+WtYgFtX3mtfVwG8KVToArWeQoxPM58bc7E7+OZ3yPmzeu1e/o0THDd+1C3El9TdpAiluGvhtdtGTWuRcNTpSDe3RLlZ1AXxkF9+Kizw9H5aba+L1iWpRNoQ9FJ3/u9uwIlurGTmoZ9psxHurXLd8F69vyIHzQZDyqSid46wYuJYVXAleMUL3JzG5xaLAjfbyDhjQZoeFH4EqBX5cn/rnL+fp+6zLtrvnvAzk94Okux7w4Jz/6fJl8BMgOdlgxieJcHTHN7q1gl223ne7z5kB4EcN+yN3c+XwP1NLCAwYv3h+VRhL+hCRV6oGOMMT9EsTZsn9q1os4q9A22GHzupPlLd6svyo6KexQT53AmTbk33pWq+y+OykQD4Sv5g8/zuhZEiFGfXchfUxuM8=
  template:
    metadata:
      name: qbittorrent-pia-vpn-creds
      namespace: media
    type: Opaque
