---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-pia-vpn-creds
  namespace: media
spec:
  encryptedData:
    password: AgA5GAevegBr2DuopDcubrDkUMcNM7keTfb7nzCNKQahd04ySeDPp5z0F612q3nTSMyVaEh5jFX5gPiAttv2snKVXX0upf3/lIvNc36Hk7CbAwiA9O4EX9Z3nS52hU7hjYjsJ4vR7lsKJJGhXJfSE1V7D4s3w9JAoiEJIqARG2fOt4yMiYK2HWIpGJQfneT8Rp21bYuJWt/2MMVcgcBwp+az3HTw9B0q2/a2pw0BPeiBN1U32YYjMokwWwKe4bqFfOMrO4ZuSkY4jPkrMLbS5x9hQJBojcP9Gx4tE1CsbPmndodJdMYGP8EN77qjgyRdhS5JPX/ShlKDEPumponfgwYrxR/ww1+3bom3hMLp6bLoNKMs7g9JC/ukYJZoznbY/6h3tb8+TV3xLtCLfA3eS/lGrKO4WW0MApJTUVcs+MW+iRCzCsT/jxSb3RSuWMHZpRksQe0NPijaPWS9VFPjhfDkTaYVADv9HUWPuozHxkYwJnWnT5P8L/KVZ55umUx3K3PBEda/Thnhbs3Y8U/nymYi5PK06jcr8tVc6p3mq9c/ns7UiFENYPNHH6mf4GCgH4bEZcuvUotfKJC8X+z7EGBQqTz958PnV+ohjcfWDg6zglOLpXtDYo07GNm4ULb5yEIvT1iice4Tob4Yta+3LWgu2PTkN7RO0U0JyQlfzf8kaZxiWrDoV7k9yG8vtzp+OYZkr7sFujaBmfGwqQ==
    username: AgBqQULbJjbMXl5Py/XK2psxCZd5gEhfgqUnISTuXsDT3SxoDjIUh9zRtTtyGntWGIq7DSkDI1xp0xoAfcN1wM1bKQVST99B7qQpSifjhihght+JChsPUjYujeSc4ds4Hgq0RZy41fH7Neq62+OJnUArnnzobngnPZdINOMENfDAMUmHJqzBXBKWBHNcbCFwZ7asWIgHf9+yi7GYn502N87ZiuSbPuuTSdiBNt+vTyIsBuR34XhmNlY4nhsp04kKx6zq60wiiDNiIS7oueosft6FZE9VXTdbjnNt4s/uK3RMU4XrvXGXSbIYdI8OpTfQUpESk4LaENJJH+BXSnm/5FagoIZmCxP9vC2dgMcCFFluZeehsNym3LsgURQArnEK9IN43Kp5WjeTIQVuXeJZsD37sPv9jLyTPbLFh6kG1PDQxXvuaDKoUhoO2fQzfSlezqBtFfNqfY/skQN3EfGvNFJVWI/DUbtWqnHRmankX6K8vjrBwGmj9p1B67/Ioz7elAlynFyLkc+T/HzRUeqP3ZPXcfdyaH48H2kRh0BJL4uhb4jfxX0YlxBb/2II7jpZYi+uGOySktsQnY+KK7reBHQgDvA9+TXCe1okaABVjvmpmUY/4AnkwOG4KbDMU38a2BpowAvl1WRieGKB8qHHGkZaQGTCnapm17DF7P6BPPJk4sUaxvb9ItfYpu3+t/+sN+sRLKZ3GlFoG1o=
  template:
    metadata:
      name: qbittorrent-pia-vpn-creds
      namespace: media
    type: Opaque
