---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

# insert a separate file as a configmap
configMapGenerator:
- name: homer-configmap
  files:
  - config.yml

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: homer

resources:
- ../../base

namePrefix: prd-

patches:
- path: volumes.yml
- path: svc_port.yml