---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-test

# # insert a separate file as a configmap
# configMapGenerator:
# - name: syncthing-configmap
#   files:
#   - config.xml

# # needed for pruning in the Jenkinsfile
# generatorOptions:
#   labels:
#     app: syncthing

resources:
- ../../base

namePrefix: dev-

patches:
- path: svc_IP.yml
