---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-sync
  namespace:  bots
  labels:
    app: nebula-sync
spec:
  selector:
    matchLabels:
      app: nebula-sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nebula-sync
    spec:
      restartPolicy: Always
      containers:
        - name: nebula-sync
          image: ghcr.io/lovelaze/nebula-sync:v0.11.2
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 1
              memory: 128Mi
          # load all env vars from configmap
          envFrom:
            - configMapRef:
                name: nebula-sync-env
          env:
          - name: PRIMARY
            valueFrom:
              secretKeyRef:
                name: nebula-piholes
                key:  pihole_primary
          - name: REPLICAS
            valueFrom:
              secretKeyRef:
                name: nebula-piholes
                key:  pihole_replicas


                