---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nebula-piholes
  namespace: bots
spec:
  encryptedData:
    pihole_primary: AgBdC5xOiWjj5ZNPXztzchO9VtFE1tLuHU8QOPm1bNWRGto+Stt2sMokVv614KthEOsqMuI0sZZLR4D6t3BPp9HH/kyuDEBK2awl1bH+llW1w7MK4bx6PZe0GJbdURXgBT1uP0dy8zpkzKGYeFB3Ouy3uzA5C3TX7JUtY/kmuPOkYTJVM0Vt0w/NInOXJfJUb/xY8srS32x7lt7pHATuDal8mz2BEvJWMqi5JkCXKlY8ggFz5okIEi2bVwgfE1ajKoqBpLYOTuyX6+Dg+KGIyLuc/B+YnOs29VoZ62uSVbXPrXG7myToKDoIQBRoTxQa4n58tAnAfXouzc0Nvb/GnnsaFPrSNAoURVVWeVBbjfdgrmCbjKV9jr0cJ5AKUC1rzaCnOwjOrExEk3hCDSrKVQM7cBzRxT4lAkCEWMFf/YHpDxORKlhgQJWnzUqzIKycRaZxi6dGGv/13gj7XpIQ9TckVRn01KsSdBBTuFPFCkoW/uwUizp1x8YpSs11rR4rQRAjPd9rKIlQ1bkQ+eLNdXkBnDpzCB+bhEuURK8LiPA2wFtrKVE5zSGCNajj50wSfdZtQOevMcrYDcEkZ4lNJ0Oy5ZfnyxapreUEbiz+e+0SHibqmXeW7sRHiggUVVFFInk+xMXMss8J9NL70U6BhFyHHxV8fZ5qm2RbROWoDz3dqewFX1ZMMOrcr+5RxkMvq7+lMdbL5kiLR2EI/fUm00HzHQsxm1qIW3nY1rxLZvxTcwr5k+DNMBbOjto+2dcwBkIqKGvw8CxwCxRybS8p/QqZmYE=
    pihole_replicas: AgB2GwyNGjJD5YzRFSscHJsubRJVu+m4GtXEaqAQK4Xccci1y0iJ/URaDZ666Ox97EaF4iyxlr5FoSfMPe4iUMZMFXiQGvmbsw5z1RIHuMnevxfGO6pM/ALX6EGMIkG+hgwf565xRAEuX1cNhXYVs4u8FqM2LjLC9i81NW5rYxojoE9Tjvyue5zz1LtxBpC/svYUT/u5q5zdGgeRehmJxQYCAKk3JogR9jhKCiZSqmEG+iF3duRE4VP2qRE7+EDZ9ynVk3jWuuzXST4QT1pAzeAskH6SMp0pSEX69vKi6TXC8E6OjnhiKCfF8HUhn1XUs+1wM/KTN+Ccsvd6iUkoyGCkfyLd1py4tq8ugIMOJUXrelQah/uuQlXo5e5wkfEX9aI+KiksLG7JpnexMknQfOvSCqdB2O5lyBSIkaCyMksmSYHB00TW0oUDbgevcU1jdveyc+LrQpTHO3cfBzNL9lzsn9RE0VqSZvw4W6kuw/1W0ECOItvjQW9J0C/Q8Dm0w+HA++EF7ba60TG0ComwBph7dQ05czEomnvacYCtU6LREAcXdh30+vZjftbzcg5S4R6vSCeDv75e8AEL+GpybitfrVtjHt2afXooNDCAz3aM9YfMUE5fQ5vOx62Zib6dh6YiRS0wftci3F7ujM/cOzJ9PVVD0iwbYt8+OdYQ+2htUjdfWBZDvjXN9vIHBgbT7B0dDk9iPasJD1r36UtI0kwfvbbRJtq4WUFLLIBrtwA1/P6PxjiA74JxWh7SmRAjnYYCdnNktuOKQxUc+WpaTlQj4Sg=
  template:
    metadata:
      name: nebula-piholes
      namespace: bots
    type: Opaque
