---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace:  applications
  annotations:
    metallb.universe.tf/allow-shared-ip: "syncthing-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: syncthing
  ports:
    - name: sync-web
      port: 8384
      targetPort: 8384
    - name: sync-listen-tcp
      port: 22000
      targetPort: 22000
      protocol: TCP
    - name: sync-listen-udp
      port: 22000
      targetPort: 22000
      protocol: UDP
    - name: sync-discovery
      port: 21027
      targetPort: 21027
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 192.168.13.29