---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-testing
  labels:
    app: nginx-testing
spec:
  selector:
    matchLabels:
      app: nginx-testing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-testing
    spec:
      restartPolicy: Always
      containers:
        - name: nginx-testing
          image: nginx:1.27@sha256:447a8665cc1dab95b1ca778e162215839ccbb9189104c79d7ec3a81e14577add
          ports:
            - containerPort: 8080