---
apiVersion: v1
kind: Service
metadata:
  name: nginx-testing
  annotations:
    metallb.universe.tf/allow-shared-ip: "nginx-testing-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: nginx-testing
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer