---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  applications

resources:
  - deployment.yml
  - service.yml
  - pvc.yml

# insert a separate file as a configmap
configMapGenerator:
- name: navidrome-configmap
  files:
  - navidrome.toml