---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config-data
  namespace:  media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-nfs-bkup-pvc
  namespace:  media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
  volumeName: navidrome-nfs-bkup-pv