---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      restartPolicy: Always
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.7@sha256:746601dcc9dd95b3e2703c0244e453653d29b064281f7a9174d2d24d2aba81ef
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 8989
          volumeMounts:
          - name: sonarr-shows-nfs
            mountPath:  /tv
          - name: sonarr-downloads-nfs
            mountPath:  /downloads
          - name: sonarr-config
            mountPath:  /config
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: TZ
            value:  America/New_York
      volumes:
        - name: sonarr-shows-nfs
          hostPath:
            path: /mnt/mobius/Video/TV-shows
            type: Directory
        - name: sonarr-downloads-nfs
          hostPath:
            path: /mnt/mobius/temp/transmission
            type: Directory
        - name: sonarr-config
          persistentVolumeClaim:
            claimName:  sonarr-config-pvc