---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

# insert a separate file as a configmap
configMapGenerator:
- name: syncthing-configmap
  files:
  - config.xml

# needed for pruning in the Jenkinsfile
generatorOptions:
  labels:
    app: syncthing

resources:
- ../../base

namePrefix: prd-

patches:
- path: svc_IP.yml