---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-metallb-ip"  
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: unifi
  ports:
    - name: unifi-web-admin
      port: 8443
      targetPort: 8443
    - name: unifi-stun
      port: 3778
      targetPort: 3778
      protocol: UDP
    - name: unifi-ap-discovery
      port: 10001
      targetPort: 10001
      protocol: UDP
    - name: unifi-dev-comm
      port: 8080
      targetPort: 8080
    - name: unifi-l2-discovery
      port: 1900
      targetPort: 1900
      protocol: UDP
    - name: unifi-guest-https
      port: 8843
      targetPort: 8843
    - name: unifi-guest-http
      port: 8880
      targetPort: 8880
    - name: unifi-mobile
      port: 6789
      targetPort: 6789
    - name: unifi-syslog
      port: 5514
      targetPort: 5514
      protocol: UDP
  type: LoadBalancer