---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytdl
spec:
  template:
    spec:
      volumes:
        - name: ytdl-appdata-nfs
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/ytdl/appdata
        - name: ytdl-audio-nfs
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/ytdl/audio
        - name: ytdl-video-nfs
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/ytdl/video
        - name: ytdl-subs-nfs
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/ytdl/subscriptions