---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: languagetool-ngram-pvc
  namespace:  applications
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: languagetool-fasttext-pvc
  namespace:  applications
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi