---
apiVersion: v1
kind: Service
metadata:
  name: languagetool
  namespace:  applications
  annotations:
    metallb.universe.tf/allow-shared-ip: "languagetool-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: languagetool
  ports:
    - name: languagetool
      port: 8010
      targetPort: 8010
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.13.235