---
apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: homer
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---
# apiVersion: apps/v1
apiVersion: v1
# kind: Deployment
kind: Pod
metadata:
  name: homer
spec:
  selector:
    matchLabels:
      app: homer
  # replicas: 2
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: b4bz/homer:latest
          ports:
            - containerPort: 8080
  # /docker/docker-compose/homer/assets/:/www/assets
  volumeMounts:
  - name: homer-pvc
    mountPath: /www/assets
  volumes:
  - name: homer-pvc
    persistentVolumeClaim:
      claimName: homer-longhorn-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi