---
apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: homer
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.13.32

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  labels:
    app: homer
  namespace: default
spec:
  selector:
    matchLabels:
      app: homer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homer
    spec:
      restartPolicy: Always
      containers:
        - name: homer
          image: b4bz/homer:latest
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: homer-vol
            mountPath: /www/assets
      volumes:
        - name: homer-vol
          persistentVolumeClaim:
            claimName: homer-pvc

