---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-test

configMapGenerator:
- name: homer-configmap
  files:
  - config.yml

generatorOptions:
  labels:
    app: homer

resources:
- ../../base

namePrefix: dev-

patches:
- path: volumes.yml
- path: svc_port.yml