---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
spec:
  template:
    spec:
      volumes:
        - name: homer-png-nfs
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/kustomize/homer/assets/png
        - name: homer-svg-nfs
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/kustomize/homer/assets/svg