---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace:  media
  labels:
    app: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      restartPolicy: Always
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:5.19.3@sha256:0a8020afc5e3dcad1413ba125a980729a2b16ff0d88d108b3e1779111ef1c896
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 7878
          volumeMounts:
          - name: radarr-movies-nfs
            mountPath:  /movies
          - name: radarr-downloads-nfs
            mountPath:  /downloads
          - name: radarr-config
            mountPath:  /config
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: TZ
            value:  America/New_York
      volumes:
        - name: radarr-movies-nfs
          hostPath:
            path: /mnt/mobius/Video/Movies
            type: Directory
        - name: radarr-downloads-nfs
          hostPath:
            path: /mnt/mobius/temp/qflood/downloads
            type: Directory
        - name: radarr-config
          persistentVolumeClaim:
            claimName:  radarr-config-pvc