---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      restartPolicy: Always
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:1.21.2.4649-ls82@sha256:c80a2dcfefd85c62da2373c5bf0138bb9d1c647c4b3d8f994ce263f5e8b1db81
          resources:
            limits:
              cpu: 8
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 9696
          volumeMounts:
          - name: prowlarr-config
            mountPath: /config
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: TZ
            value:  America/New_York
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName:  prowlarr-pvc