---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  annotations:
    metallb.universe.tf/allow-shared-ip: "prowlarr-metallb-ip"  
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: prowlarr
  ports:
    - name: prowlarr-ui
      port: 9696
      targetPort: 9696
  type: LoadBalancer