---
version: "3"
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:8.3.32-ls56@sha256:fb219c24c81acbf9b0d56af308fe9fe5fd93411823a26bf5bfdfe8adcefc36e9
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MONGO_USER=unifi
      - MONGO_PASS=sAqTwsP6NcvsJc9un5Kbv8yK4eVTf87C
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    volumes:
      - /docker/docker-compose/unifi-net-app/config:/config
    ports:
      - 8443:8443       # Unifi web admin port
      - 3478:3478/udp   # Unifi STUN port
      - 10001:10001/udp # Required for AP discovery
      - 8080:8080       # Required for device communication. alread in use. change to 8082?
      - 1900:1900/udp   # optional, Required for `Make controller discoverable on L2 network` option
      - 8843:8843       # optional, Unifi guest portal HTTPS redirect port
      - 8880:8880       # optional, Unifi guest portal HTTP redirect port
      - 6789:6789       # optional, For mobile throughput test
      - 5514:5514/udp   # optional, Remote syslog port
    restart: unless-stopped

  # container requires an external mongoDB
  unifi-db:
    # image: docker.io/mongo:4.4@sha256:6968605d75f9ed587adf94ffac5c18963a3dcdd13892f91412bccfa80059265a # max supported version is 4.4
    # image: docker.io/mongo:latest@sha256:ae1cf99fa7bfb007db8416ad4f3980c46054d949fa55d28e6d301a813fee6c06 # max supported version is 4.4
    container_name: unifi-db
    volumes:
      - /docker/docker-compose/unifi-net-app/data:/data/db
      - /docker/docker-compose/unifi-net-app/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped