---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace:  media
  labels:
    app: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      restartPolicy: Always
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.3.0@sha256:e50f3b188a7d1771b61f395c4203e35476bd3047683508740305e830e15bacf7
          resources:
            limits:
              cpu: 8
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 9696
          volumeMounts:
          - name: prowlarr-config
            mountPath: /config
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: TZ
            value:  America/New_York
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName:  prowlarr-pvc