---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace:  media
  labels:
    app: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      restartPolicy: Always
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.5.2@sha256:1295cff29d10b486c0d8324d1559a552140a5932bf8b3d87e398654414f63f92
          resources:
            limits:
              cpu: 8
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 9696
          volumeMounts:
          - name: prowlarr-config
            mountPath: /config
          - name: prowlarr-backup
            mountPath:  /config/Backups
          env:
          - name: PUID
            value:  "1000"
          - name: PGID
            value:  "1000"
          - name: TZ
            value:  America/New_York
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName:  prowlarr-pvc
        - name: prowlarr-backup
          persistentVolumeClaim:
            claimName:  prowlarr-nfs-bkup-pvc