---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace:  media
  annotations:
    metallb.universe.tf/allow-shared-ip: "prowlarr-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: prowlarr
  ports:
    - name: prowlarr-ui
      port: 9696
      targetPort: 9696
  type: LoadBalancer
  loadBalancerIP: 192.168.13.31