---
apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: homer
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.13.20

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  labels:
    app: homer
  namespace: default
spec:
  selector:
    matchLabels:
      app: homer
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: homer
    spec:
      os: { name: linux }
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      containers:
        - name: homer
          image: b4bz/homer:latest
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: homer-nfs
            mountPath: /www/assets
      volumes:
        - name: homer-nfs
          hostPath:
            path: /mnt/k3s-data/dev-test/apps/homer/assets/
            type: Directory
