---
apiVersion: v1
kind: Service
metadata:
  name: whisparr
  namespace:  media
  annotations:
    metallb.universe.tf/allow-shared-ip: "whisparr-metallb-ip"  
spec:
  ipFamilyPolicy: SingleStack
  selector:
    app: whisparr
  ports:
    - name: whisparr-ui
      port: 6969
      targetPort: 6969
  type: LoadBalancer
  loadBalancerIP: 192.168.13.42